---
- name: Install HTTP SERVER
  become: yes
  hosts: all

  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes 
...

