---
- name: Install HTTP SERVER
  become: yes
  hosts: g2

  tasks:
    - name: Install HTTPD
      dnf:
        name: httpd
        state: present
      when: ansible_distribution == "Red Hat"

    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes 
      when: ansible_distribution == "Red Hat"


- name: Install apache
  apt:
    name: apache2
    state: present
  when: ansible_distribution == "Ubuntu"
    
- name: start apache2
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"      
...