---
- name: Variable Demo
  become: yes
  hosts: g2
  vars:
  myusername: wole

  tasks:
    - name: update dynamic page
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
        
...